const LANGS = {
	"NOT_TRANSLATEABLE": {
		ProxifyURSELF: "Proxify URSELF! - By ",
		WhiteList: "WhiteList",
		ON: "ON",
		on: "On",
		whitelist: "WhiteList",
		StuckDetectorSlider: "Stuck Detector"
	},
	
	
	"ru": {
		LaungageName: "Russian",
		"Mode-WhiteList": 'Режим "Белый список"',
		WhiteListDescription: 'VPN для определённого списка сайтов',
		VPN4All: "VPN для всех сайтов",
		OpenSettings: "Открыть настройки",
		Settings: "Настройки",
		GiveMeASecond: "Секунду...",
		EnableVPN: "Включить VPN",
		DisableVPN: "Отключить VPN",
		InsertConfigurationCode: "Для продолжения введите код конфигурации: ",
		Continue: "Продолжить",
		Disable: "Отключить",
		Cancel: "Отмена",
		WhiteListEdit: "Белый список",
		DisableOtherVPNTitle: "Отключите другие VPN :(",
		DisableOtherVPN: "Мы обнаружили что другие VPN - расширения препятствуют работе Ownify. А именно:",
		UpdatableWhiteList: "Обновляемый WhiteList",
		UpdatableWhiteListDescription: `Постоянно дополнять список WhiteList на основе <a href="https://github.com/0mnr0/ownify" target="_blank"> репозитория</a>. Не заменяет вручную добавленные сайты`,
		StuckDetector: "Если сайт не загружается - будет предложено добавить сайт в WhiteList. (Только HTTPS сайты)",
		ChangeConfiguration: "Изменить конфигурацию",
		AddAndReload: "Добавить и перезагрузить",
		ignoreThisSite: "Не предлагать для этого сайта",
		PageIsNotLoading: "Страница не загружается :(",
		ResetIgnoringSites: "Сбросить список игнорируемых сайтов",
		UpdateGITListNow: "Обновить список сейчас",
		UserAgentDescription: 'Подмена браузера на самый популярный. Уменьшает шансы на капчу',
		WebRTC_Setting: 'Отключить WebRTC',
		WebRTC_Description: 'Исправляет "Утечку" реального IP адреса, но соединение становится медленнее',
		disabledAll: 'Отключено всё!',
		stuckMessage: 'Не загружается. Добавить в белый список и открыть заново?',
		Mode: 'Режим',
		InterstingFact: "Интересный факт:",
		WhatAboutFact: "Каждый значок появляющийся на экране, означает что какой-то сайт выполнил запрос:",
		RequestWithVpn: "С использованием VPN",
		RequestWithoutVPN: "Без VPN",
		ListIgnoringSitesReseted: "Список игнорируемых сайтов сброшен!",
		SearchInWhiteList: "Поиск в белом списке",
		IncorrectSyntax: 'Неверный синтаксис',
		ListWasUpdated: "Список обновлен!"
	},
	"en": {
		LaungageName: "English",
		"Mode-WhiteList": '"WhiteList" Mode',
		WhiteListDescription: 'VPN only for listed sites',
		VPN4All: "VPN for all sites",
		OpenSettings: "Open Settings",
		Settings: "Settings",
		EnableVPN: "Enable VPN",
		DisableVPN: "Disable VPN",
		GiveMeASecond: "Second...",
		InsertConfigurationCode: "To continue, enter configuration into field: ",
		Continue: "Continue",
		Disable: "Disable",
		Cancel: "Cancel",
		WhiteListEdit: "White List",
		DisableOtherVPNTitle: "Disable other VPN :(",
		DisableOtherVPN: "We found that other VPN extensions are preventing Ownify from working. Exactly:",
		UpdatableWhiteList: "Updatable WhiteList",
		UpdatableWhiteListDescription: `Constantly update the WhiteList based on <a href="https://github.com/0mnr0/ownify " target="_blank"> repositories</a>. It does not replace manually added sites`,
		StuckDetector: "If the site does not load, you will be prompted to add the site to the WhiteList. (HTTPS sites only)",
		ChangeConfiguration: "Change configuration",
		AddAndReload: "Add and reload",
		ignoreThisSite: "Do not suggest for this site",
		PageIsNotLoading: "The page won't load :(",
		ResetIgnoringSites: "Reset the list of ignored sites",
		UpdateGITListNow: "Update the list now",
		UserAgentDescription: 'Replacing the browser with the most popular one. Reduces the chances of a captcha',
		WebRTC_Setting: 'Disable WebRTC',
		WebRTC_Description: 'Fixes the "Leak" of the real IP address, but the connection becomes slower',
		disabledAll: 'Disabled All!',
		stuckMessage: `won't load. Add to the whitelist and reopen?`,
		Mode: 'Mode',
		InterstingFact: "Intersting fact:",
		WhatAboutFact: "Each icon that appears on the screen means that some website has completed the request:",
		RequestWithVpn: "Using VPN",
		RequestWithoutVPN: "Without VPN",
		ListIgnoringSitesReseted: "The list of ignored sites has been reset!",
		SearchInWhiteList: "Search in white list",
		IncorrectSyntax: 'Incorrect Syntax',
		ListWasUpdated: "Last was updated!"
	}
}